#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# Wait for celery worker to be ready (optional but good practice)
# sleep 5

/entrypoint celery -A config flower \
    --basic_auth="${CELERY_FLOWER_USER}:${CELERY_FLOWER_PASSWORD}"
