# Generated by Django 6.0.1 on 2026-01-13 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
        ('submissions', '0002_rename_response_answer_submission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='invitation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission', to='communications.invitation'),
        ),
    ]
