# Generated by Django 6.0.1 on 2026-01-09 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='configuration',
        ),
        migrations.RemoveField(
            model_name='questionlogic',
            name='target_section',
        ),
        migrations.AddField(
            model_name='question',
            name='identifier',
            field=models.SlugField(blank=True, help_text='Unique string to identify the question in logic strings or API.', max_length=100, null=True, verbose_name='Identifier'),
        ),
        migrations.AlterField(
            model_name='questionlogic',
            name='action',
            field=models.CharField(choices=[('show', 'Show Question'), ('hide', 'Hide Question'), ('include_choices', 'Include Specific Choices'), ('exclude_choices', 'Exclude Specific Choices')], max_length=20),
        ),
        migrations.AlterField(
            model_name='questionlogic',
            name='operator',
            field=models.CharField(choices=[('eq', 'Equals'), ('neq', 'Not Equals'), ('gt', 'Greater Than'), ('lt', 'Less Than'), ('contains', 'Contains')], max_length=10),
        ),
        migrations.AlterField(
            model_name='questionlogic',
            name='target_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logic_targets', to='surveys.question'),
        ),
        migrations.AlterField(
            model_name='questionlogic',
            name='trigger_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logic_triggers', to='surveys.question'),
        ),
        migrations.CreateModel(
            name='QuestionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='', max_length=255, verbose_name='Label')),
                ('label_en', models.CharField(default='', max_length=255, null=True, verbose_name='Label')),
                ('label_ar', models.CharField(default='', max_length=255, null=True, verbose_name='Label')),
                ('value', models.CharField(default='', max_length=255, verbose_name='Value')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_choices', to='surveys.question')),
            ],
            options={
                'verbose_name': 'Question Choice',
                'verbose_name_plural': 'Question Choices',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='questionlogic',
            name='target_choices',
            field=models.ManyToManyField(related_name='question_logics', to='surveys.questionchoice'),
        ),
    ]
