#!/bin/bash

export DJANGO_SETTINGS_MODULE=config.settings.production

set -o errexit
set -o pipefail
set -o nounset

/entrypoint celery -A config flower \
    --basic_auth="${CELERY_FLOWER_USER}:${CELERY_FLOWER_PASSWORD}"
