#!/bin/bash

# Set the Django settings module to production
export DJANGO_SETTINGS_MODULE=config.settings.production

set -o errexit
set -o pipefail
set -o nounset

/entrypoint celery -A config worker -l info
